[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
rand = "0.8.0"
rand_chacha = "0.3.1"

[feature]
dev_mode = ["bevy/bevy_dev_tools", "other_dev_tools"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
